---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php7.2-mysql
    - python-mysqldb

- name: starting mysql server
  service:
    name: mysql
    state: started
    enabled: yes
     
