- hosts: '{{ hosts }}'
  gather_facts: False
  remote_user: '{{ user }}'
  vars:
    ansible_become_pass: '{{ pass }}'
  roles:
    - php
    - wordpress


- hosts: '{{ hosts }}'
  gather_facts: False
  remote_user: '{{ user }}'
  vars:
    ansible_become_pass: '{{ pass }}'
  roles:
    - server 
    - mysql 
